name: Deploy MkDocs

on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'
      - 'mkdocs.yml'
      - 'assets/**'

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          pip install mkdocs mkdocs-material
      - name: Deploy to GitHub Pages
        run: |
          mkdocs gh-deploy --force --remote-name origin
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
